Resources:
  BukcetRolodu0228AE60:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: SimpleAppStack/BukcetRolodu/Resource
  getPhotosServiceRoleA672FDB6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SimpleAppStack/getPhotos/ServiceRole/Resource
  getPhotosE6AA305E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeS3Bucket909BCEB9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeS3VersionKey10147753
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeS3VersionKey10147753
      Role:
        Fn::GetAtt:
          - getPhotosServiceRoleA672FDB6
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.main
      Runtime: nodejs14.x
    DependsOn:
      - getPhotosServiceRoleA672FDB6
    Metadata:
      aws:cdk:path: SimpleAppStack/getPhotos/Resource
      aws:asset:path: /home/jordhan/projetos/cdk-projects/simple-app/cdk/cdk.out/asset.af999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afe
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAA02OSw7CMAwFz8LeNQSExJKPxBJQOUFIDUpLExQ7sIhyd5oCEqtna/TGVqhmK1STtX5xZZpumowPhOks2nSw844lRCOwu7pjlEcU2DCTDPhm3Q1qYh+DocJPOuiehEJZ/sFgaaxY7zKUK4kXmLbRdDRqP1OGu+4vja6cb6hlPIyxj86UIljdY6r9ffSVzMCLSpdXGMePvn0c+K+VMxQbtjx9qjmqJc4mLVtbhejE9oT1J98644YzBAEAAA==
    Metadata:
      aws:cdk:path: SimpleAppStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  BukcetRoloduNameExport:
    Description: BIRULEIBIS
    Value:
      Ref: BukcetRolodu0228AE60
    Export:
      Name: BukcetRoloduNameExport
Parameters:
  AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeS3Bucket909BCEB9:
    Type: String
    Description: S3 bucket for asset "af999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afe"
  AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeS3VersionKey10147753:
    Type: String
    Description: S3 key for asset version "af999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afe"
  AssetParametersaf999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afeArtifactHash74BE7EFB:
    Type: String
    Description: Artifact hash for asset "af999c4d2ed0bfc94d7995785ea24e55fd195412e7be86bd494a00cd51c61afe"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

